// <auto-generated />
using System;
using ElevatorSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElevatorSystem.Migrations
{
    [DbContext(typeof(ElevatorDbContext))]
    partial class ElevatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElevatorSystem.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Building", (string)null);
                });

            modelBuilder.Entity("ElevatorSystem.Models.Elevator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int")
                        .HasColumnName("BuildingID");

                    b.Property<int>("CurrentFloor")
                        .HasColumnType("int");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoorStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BuildingId" }, "FK_Building")
                        .IsUnique();

                    b.ToTable("Elevator", (string)null);
                });

            modelBuilder.Entity("ElevatorSystem.Models.ElevatorCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CallTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("DestinationFloor")
                        .HasColumnType("int");

                    b.Property<bool>("IsHandled")
                        .HasColumnType("bit");

                    b.Property<int>("RequestedFloor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("ElevatorCall", (string)null);
                });

            modelBuilder.Entity("ElevatorSystem.Models.ElevatorCallAssignment", b =>
                {
                    b.Property<int>("CallID")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignmentTime")
                        .HasColumnType("datetime");

                    b.Property<int>("ElevatorCallId")
                        .HasColumnType("int");

                    b.Property<int>("ElevatorId")
                        .HasColumnType("int");

                    b.HasKey("CallID");

                    b.HasIndex("ElevatorCallId");

                    b.HasIndex("ElevatorId");

                    b.ToTable("ElevatorCallAssignment", (string)null);
                });

            modelBuilder.Entity("ElevatorSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ElevatorSystem.Models.Building", b =>
                {
                    b.HasOne("ElevatorSystem.Models.User", "User")
                        .WithMany("Buildings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Building_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ElevatorSystem.Models.Elevator", b =>
                {
                    b.HasOne("ElevatorSystem.Models.Building", "Building")
                        .WithOne("Elevator")
                        .HasForeignKey("ElevatorSystem.Models.Elevator", "BuildingId")
                        .IsRequired()
                        .HasConstraintName("FK_Elevator_Building");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ElevatorSystem.Models.ElevatorCall", b =>
                {
                    b.HasOne("ElevatorSystem.Models.Building", "Building")
                        .WithMany("ElevatorCalls")
                        .HasForeignKey("BuildingId")
                        .IsRequired()
                        .HasConstraintName("FK_ElevatorCall_Building");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ElevatorSystem.Models.ElevatorCallAssignment", b =>
                {
                    b.HasOne("ElevatorSystem.Models.ElevatorCall", "ElevatorCall")
                        .WithOne()
                        .HasForeignKey("ElevatorSystem.Models.ElevatorCallAssignment", "CallID")
                        .IsRequired()
                        .HasConstraintName("FK_ElevatorCallAssignment_ElevatorCall");

                    b.HasOne("ElevatorSystem.Models.ElevatorCall", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ElevatorCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElevatorSystem.Models.Elevator", "Elevator")
                        .WithMany("Assignments")
                        .HasForeignKey("ElevatorId")
                        .IsRequired()
                        .HasConstraintName("FK_ElevatorCallAssignment_Elevator");

                    b.Navigation("Elevator");

                    b.Navigation("ElevatorCall");
                });

            modelBuilder.Entity("ElevatorSystem.Models.Building", b =>
                {
                    b.Navigation("Elevator");

                    b.Navigation("ElevatorCalls");
                });

            modelBuilder.Entity("ElevatorSystem.Models.Elevator", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("ElevatorSystem.Models.ElevatorCall", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("ElevatorSystem.Models.User", b =>
                {
                    b.Navigation("Buildings");
                });
#pragma warning restore 612, 618
        }
    }
}
